import com.redis._
val r = new RedisClient("ec2-52-54-82-137.compute-1.amazonaws.com", 6379, 0, Option("BFHW6zDv3g7kuxDxRXV7K8Y2pdyfR7kw"))
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,anomalous")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,anomalous")
r.publish("tcp.http","tcp,http,anomalous")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,anomalous")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")
r.publish("tcp.http","tcp,http,normal")

