alias kafka-topics='/usr/local/kafka/bin/kafka-topics.sh --list --zookeeper localhost:2181'
alias submit-consumer='/usr/local/spark/bin/spark-submit --class TrafficDataStreaming --master spark://ip-172-31-0-6:7077 --jars target/scala-2.10/price_data-assembly-1.0.jar target/scala-2.10/price_data_2.10-1.0.jar'
alias submit-kmeans='/usr/local/spark/bin/spark-submit --class StreamingKMeans --master spark://ip-172-31-0-6:7077 --jars target/scala-2.10/price_data-assembly-1.0.jar target/scala-2.10/price_data_2.10-1.0.jar'
alias start-producer='~/opt/realtimeAnomalies/src/main/producer/spawn_kafka_streams.sh 23.22.195.205 4 k1'
alias ll='ls -la --block-size=M'
alias kafka-clear='/usr/local/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic traffic_data --config retention.ms=1000'
alias kafka-restore='/usr/local/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --alter --topic traffic_data --config retention.ms=86400000'
alias hdfs='/usr/local/hadoop/bin/hdfs'
alias spark-shell='/usr/local/spark/bin/spark-shell  --master spark://ip-172-31-0-6:7077 --jars target/scala-2.10/price_data-assembly-1.0.jar target/scala-2.10/price_data_2.10-1.0.jar'
alias test-data-url='hdfs://ec2-23-22-195-205.compute-1.amazonaws.com:9000/data/kddcup.testdata.unlabeled'
export hdfs_root='hdfs://ec2-23-22-195-205.compute-1.amazonaws.com:9000/'
alias clear-hdfs='/usr/local/hadoop/bin/hdfs dfs -rm -r /test/* && /usr/local/hadoop/bin/hdfs dfs -rm -r /train/*'
alias move-training='/usr/local/hadoop/bin/hdfs dfs -mv /data/unlabeled_full_numeric /train/unlabeled_full_numeric'
alias move-test='/usr/local/hadoop/bin/hdfs dfs -mv /data/unlabeled_test_numeric /test/unlabeled_test_numeric'
alias move-restore='/usr/local/hadoop/bin/hdfs dfs -mv /train/unlabeled_full_numeric /data/unlabeled_full_numeric && /usr/local/hadoop/bin/hdfs dfs -mv /test/unlabeled_test_numeric /data/unlabeled_test_numeric'